SetNumber("Parameters/Mesh size (m)", 0.025);
SetNumber("Parameters/Rotor angle (deg)", 26.666666666666668);
SetNumber("Parameters/Excitation event index", 2);
SetNumber("Parameters/Major-minor offset (deg)", 13.3333333333);
SetNumber("Parameters/Stator phase (deg)", 0);
SetNumber("Parameters/Rotor phase (deg)", 0);
SetNumber("Parameters/Air outer radius (m)", 0.14);
SetNumber("Parameters/Air z minimum (m)", -0.12);
SetNumber("Parameters/Air z maximum (m)", 0.12);
SetNumber("Parameters/Front plane z (m)", 0.035);
SetNumber("Parameters/Back plane z (m)", -0.035);
SetNumber("Parameters/Rotor core inner radius (m)", 0.048);
SetNumber("Parameters/Rotor core radial depth (m)", 0.02);
SetNumber("Parameters/Stator core inner radius (m)", 0.078);
SetNumber("Parameters/Stator core radial depth (m)", 0.022);
SetNumber("Parameters/Coil radial depth (m)", 0.008);
SetNumber("Parameters/Coil radial margin (m)", 0.001);
SetNumber("Parameters/Minor tangential width (m)", 0.01);
SetNumber("Parameters/Major tangential width (m)", 0.016);
SetNumber("Parameters/Rotor minor tangential width (m)", 0.008);
SetNumber("Parameters/Rotor major tangential width (m)", 0.012);
SetNumber("Parameters/Electromagnet axial length (m)", 0.03);
SetNumber("Parameters/Coil tangential margin (m)", 0.003);
SetNumber("Parameters/Rotor coil tangential margin (m)", 0.001);
SetNumber("Parameters/Coil axial margin (m)", 0.004);
Include "/workspace/geometry/patent-3890548-3d.geo";
