[package]
name = "ncollide2d_headless"
version = "0.0.0"
edition = "2018"
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
ncollide2d = { path = "../../../../../../awesome-physics-repos/ncollide/build/ncollide2d", default-features = false, features = ["dim2"] }

[profile.release]
lto = true
codegen-units = 1
panic = "abort"
opt-level = "s"
